### ISSUE TITLE
Selects which video stream 

### ISSUE THREAD

**Issue by juanchorevolution** [MahatmaX/YADrone#9]
is supposed to give the command AT \* ZAP
or base AR drone.java "next" must view certain sections of four types of video stream
only two, horizontal and vertical, but with pictures embedded simultaneous does not appear, would result very useful to see both cameras at the same time
any idea?

**Comment by MahatmaX** [comment]
That would indeed be a very nice feature to have. Unfortunately, the drone only sends one video stream at a time. One solution would be to switch between video streams very fast (e.g. 50 times per second) to display two streams with 25 frames per second each. Unfortunately, switching between streams lasts more than 1 sec. minimum. Hence I do not think this feature can be implemented :-(
